package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

    private Integer id;
    private String branchCode;
    private String branchName;
    private String branchType;
    private String address;
    private String contactNo;
    private String description;
    private boolean status;
    private Integer parentId;
    private Set<Member> members = new HashSet<>();
    private ObservableList<Branch> subBranches = FXCollections.observableArrayList();

    public Branch() {
    }

    public Branch(String branchCode, boolean status) {
        this.branchCode = branchCode;
        this.status = status;
    }

    public Branch(String branchCode, String branchName, String branchType, String address, String contactNo, String description, boolean status, Integer parentId, Set<Member> members) {
        this.branchCode = branchCode;
        this.branchName = branchName;
        this.branchType = branchType;
        this.address = address;
        this.contactNo = contactNo;
        this.description = description;
        this.status = status;
        this.parentId = parentId;
        this.members = members;
    }

    public Branch(String root) {
        
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getBranchCode() {
        return this.branchCode;
    }

    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    public String getBranchName() {
        return this.branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getBranchType() {
        return this.branchType;
    }

    public void setBranchType(String branchType) {
        this.branchType = branchType;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    public Integer getParentId() {
        return this.parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Set<Member> getMembers() {
        return this.members;
    }

    public void setMembers(Set<Member> members) {
        this.members = members;
    }

    public ObservableList<Branch> getSubBranches() {
        return subBranches;
    }

    public void setSubBranches(ObservableList<Branch> subBranches) {
        this.subBranches = subBranches;
    }
    

}
