package com.court.model;
// Generated Apr 18, 2017 4:12:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer id;
     private String branchCode;
     private String branchName;
     private String branchType;
     private String address;
     private String contactNo;
     private String description;
     private boolean status;
     private Set<Member> members = new HashSet<>();

    public Branch() {
    }

	
    public Branch(String branchCode, boolean status) {
        this.branchCode = branchCode;
        this.status = status;
    }
    public Branch(String branchCode, String branchName, String branchType, String address, String contactNo, String description, boolean status, Set<Member> members) {
       this.branchCode = branchCode;
       this.branchName = branchName;
       this.branchType = branchType;
       this.address = address;
       this.contactNo = contactNo;
       this.description = description;
       this.status = status;
       this.members = members;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getBranchType() {
        return this.branchType;
    }
    
    public void setBranchType(String branchType) {
        this.branchType = branchType;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set<Member> getMembers() {
        return this.members;
    }
    
    public void setMembers(Set<Member> members) {
        this.members = members;
    }




}


