package com.court.model;
// Generated Apr 18, 2017 4:12:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Document generated by hbm2java
 */
public class Document  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private String docCode;
     private String docName;
     private String docType;
     private Date docDate;
     private String attachPath;
     private boolean status;
     private String description;
     private Integer memeberLoanId;
    public Document() {
    }

	
    public Document(Member member, String docCode, boolean status) {
        this.member = member;
        this.docCode = docCode;
        this.status = status;
    }
    public Document(Member member, String docCode, String docName, String docType, Date docDate, String attachPath, boolean status, String description) {
       this.member = member;
       this.docCode = docCode;
       this.docName = docName;
       this.docType = docType;
       this.docDate = docDate;
       this.attachPath = attachPath;
       this.status = status;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getDocCode() {
        return this.docCode;
    }
    
    public void setDocCode(String docCode) {
        this.docCode = docCode;
    }
    public String getDocName() {
        return this.docName;
    }
    
    public void setDocName(String docName) {
        this.docName = docName;
    }
    public String getDocType() {
        return this.docType;
    }
    
    public void setDocType(String docType) {
        this.docType = docType;
    }
    public Date getDocDate() {
        return this.docDate;
    }
    
    public void setDocDate(Date docDate) {
        this.docDate = docDate;
    }
    public String getAttachPath() {
        return this.attachPath;
    }
    
    public void setAttachPath(String attachPath) {
        this.attachPath = attachPath;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getMemeberLoanId() {
        return memeberLoanId;
    }

    public void setMemeberLoanId(Integer memeberLoanId) {
        this.memeberLoanId = memeberLoanId;
    }

}


