package com.court.model;
// Generated Apr 18, 2017 4:12:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoanPayCheque generated by hbm2java
 */
public class LoanPayCheque  implements java.io.Serializable {


     private Integer id;
     private String chequeNo;
     private Date chequeDate;
     private Double chequeAmount;

    public LoanPayCheque() {
    }

    public LoanPayCheque(String chequeNo, Date chequeDate, Double chequeAmount) {
       this.chequeNo = chequeNo;
       this.chequeDate = chequeDate;
       this.chequeAmount = chequeAmount;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getChequeNo() {
        return this.chequeNo;
    }
    
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }
    public Date getChequeDate() {
        return this.chequeDate;
    }
    
    public void setChequeDate(Date chequeDate) {
        this.chequeDate = chequeDate;
    }
    public Double getChequeAmount() {
        return this.chequeAmount;
    }
    
    public void setChequeAmount(Double chequeAmount) {
        this.chequeAmount = chequeAmount;
    }




}


