package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LoanPayCheque generated by hbm2java
 */
public class LoanPayCheque implements java.io.Serializable {

    private Integer id;
    private String paymentType;
    private Date paymentRecieved;
    private String chequeNo;
    private Date chequeDate;
    private Double chequeAmount;
    private String branch;
    private String bankCode;
    private Set<LoanPayment> loanPayments = new HashSet<>();

    public LoanPayCheque() {
    }

    public LoanPayCheque(String paymentType, Date paymentRecieved, String chequeNo, Date chequeDate, Double chequeAmount, String branch, String bankCode, Set<LoanPayment> loanPayments) {
        this.paymentType = paymentType;
        this.paymentRecieved = paymentRecieved;
        this.chequeNo = chequeNo;
        this.chequeDate = chequeDate;
        this.chequeAmount = chequeAmount;
        this.branch = branch;
        this.bankCode = bankCode;
        this.loanPayments = loanPayments;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPaymentType() {
        return this.paymentType;
    }

    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    public Date getPaymentRecieved() {
        return this.paymentRecieved;
    }

    public void setPaymentRecieved(Date paymentRecieved) {
        this.paymentRecieved = paymentRecieved;
    }

    public String getChequeNo() {
        return this.chequeNo;
    }

    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }

    public Date getChequeDate() {
        return this.chequeDate;
    }

    public void setChequeDate(Date chequeDate) {
        this.chequeDate = chequeDate;
    }

    public Double getChequeAmount() {
        return this.chequeAmount;
    }

    public void setChequeAmount(Double chequeAmount) {
        this.chequeAmount = chequeAmount;
    }

    public String getBranch() {
        return this.branch;
    }

    public void setBranch(String branch) {
        this.branch = branch;
    }

    public String getBankCode() {
        return this.bankCode;
    }

    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    public Set<LoanPayment> getLoanPayments() {
        return this.loanPayments;
    }

    public void setLoanPayments(Set<LoanPayment> loanPayments) {
        this.loanPayments = loanPayments;
    }

}
