package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LoanPayment generated by hbm2java
 */
public class LoanPayment implements java.io.Serializable {

    private Integer id;
    private LoanPayCheque loanPayCheque;
    private MemberLoan memberLoan;
    private Integer installmentNo;
    private String chequeNo;
    private Integer installmentDue;
    private Double paymentDue;
    private Date paymentDate;
    private boolean isLast;
    private Double membershipFee;
    private Double savingsFee;
    private Double hoiFee;
    private Double aciFee;
    private Double optionalFee;
    private Double admissionFee;
    
    public LoanPayment() {
    }

    public LoanPayment(MemberLoan memberLoan, boolean isLast) {
        this.memberLoan = memberLoan;
        this.isLast = isLast;
    }

    public LoanPayment(MemberLoan memberLoan, Integer installmentNo, String chequeNo, Integer installmentDue, Double paymentDue, Date paymentDate, boolean isLast) {
        this.memberLoan = memberLoan;
        this.installmentNo = installmentNo;
        this.chequeNo = chequeNo;
        this.installmentDue = installmentDue;
        this.paymentDue = paymentDue;
        this.paymentDate = paymentDate;
        this.isLast = isLast;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public MemberLoan getMemberLoan() {
        return this.memberLoan;
    }

    public void setMemberLoan(MemberLoan memberLoan) {
        this.memberLoan = memberLoan;
    }

    public Integer getInstallmentNo() {
        return this.installmentNo;
    }

    public void setInstallmentNo(Integer installmentNo) {
        this.installmentNo = installmentNo;
    }

    public String getChequeNo() {
        return this.chequeNo;
    }

    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }

    public Integer getInstallmentDue() {
        return this.installmentDue;
    }

    public void setInstallmentDue(Integer installmentDue) {
        this.installmentDue = installmentDue;
    }

    public Double getPaymentDue() {
        return this.paymentDue;
    }

    public void setPaymentDue(Double paymentDue) {
        this.paymentDue = paymentDue;
    }

    public Date getPaymentDate() {
        return this.paymentDate;
    }

    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }

    public boolean isIsLast() {
        return this.isLast;
    }

    public void setIsLast(boolean isLast) {
        this.isLast = isLast;
    }

    public Double getMembershipFee() {
        return membershipFee;
    }

    public void setMembershipFee(Double membershipFee) {
        this.membershipFee = membershipFee;
    }

    public Double getSavingsFee() {
        return savingsFee;
    }

    public void setSavingsFee(Double savingsFee) {
        this.savingsFee = savingsFee;
    }

    public Double getHoiFee() {
        return hoiFee;
    }

    public void setHoiFee(Double hoiFee) {
        this.hoiFee = hoiFee;
    }

    public Double getAciFee() {
        return aciFee;
    }

    public void setAciFee(Double aciFee) {
        this.aciFee = aciFee;
    }

    public Double getOptionalFee() {
        return optionalFee;
    }

    public void setOptionalFee(Double optionalFee) {
        this.optionalFee = optionalFee;
    }

    public Double getAdmissionFee() {
        return admissionFee;
    }

    public void setAdmissionFee(Double admissionFee) {
        this.admissionFee = admissionFee;
    }

    public LoanPayCheque getLoanPayCheque() {
        return loanPayCheque;
    }

    public void setLoanPayCheque(LoanPayCheque loanPayCheque) {
        this.loanPayCheque = loanPayCheque;
    }

    
}
