package com.court.model;
// Generated Apr 18, 2017 4:12:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private Branch branch;
     private String memberId;
     private String fullName;
     private String nameWithIns;
     private String address;
     private String email;
     private String jobTitle;
     private String tel1;
     private String tel2;
     private String sex;
     private String maritalStatus;
     private Date dob;
     private Date appintedDate;
     private Date joinedDate;
     private String description;
     private String imgPath;
     private boolean status;
     private Set<MemberLoan> memberLoans = new HashSet<>();
     private Set<Document> documents = new HashSet<>();

    public Member() {
    }

	
    public Member(Branch branch, String memberId, boolean status) {
        this.branch = branch;
        this.memberId = memberId;
        this.status = status;
    }
    public Member(Branch branch, String memberId, String fullName, String nameWithIns, String address, String email, String jobTitle, String tel1, String tel2, String sex, String maritalStatus, Date dob, Date appintedDate, Date joinedDate, String description, String imgPath, boolean status, Set<MemberLoan> memberLoans, Set<Document> documents) {
       this.branch = branch;
       this.memberId = memberId;
       this.fullName = fullName;
       this.nameWithIns = nameWithIns;
       this.address = address;
       this.email = email;
       this.jobTitle = jobTitle;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.sex = sex;
       this.maritalStatus = maritalStatus;
       this.dob = dob;
       this.appintedDate = appintedDate;
       this.joinedDate = joinedDate;
       this.description = description;
       this.imgPath = imgPath;
       this.status = status;
       this.memberLoans = memberLoans;
       this.documents = documents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }
    public String getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getNameWithIns() {
        return this.nameWithIns;
    }
    
    public void setNameWithIns(String nameWithIns) {
        this.nameWithIns = nameWithIns;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getAppintedDate() {
        return this.appintedDate;
    }
    
    public void setAppintedDate(Date appintedDate) {
        this.appintedDate = appintedDate;
    }
    public Date getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(Date joinedDate) {
        this.joinedDate = joinedDate;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set<MemberLoan> getMemberLoans() {
        return this.memberLoans;
    }
    
    public void setMemberLoans(Set<MemberLoan> memberLoans) {
        this.memberLoans = memberLoans;
    }
    public Set<Document> getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Set<Document> documents) {
        this.documents = documents;
    }




}


