package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * MemberSubscription generated by hbm2java
 */
public class MemberSubscription implements java.io.Serializable {

    private Integer id;
    private String feeName;
    private String description;
    private boolean status;
    private Set<MemberSubscriptions> memberSubscriptions = new HashSet<>();

    public MemberSubscription() {
    }

    public MemberSubscription(String feeName, String description, boolean status) {
        this.feeName = feeName;
        this.description = description;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFeeName() {
        return this.feeName;
    }

    public void setFeeName(String feeName) {
        this.feeName = feeName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public boolean isStatus() {
        return this.status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

     public Set<MemberSubscriptions> getMemberSubscriptions() {
        return this.memberSubscriptions;
    }
    
    public void setMemberSubscriptions(Set<MemberSubscriptions> memberSubscriptions) {
        this.memberSubscriptions = memberSubscriptions;
    }
    
    

}
