package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MemChild generated by hbm2java
 */
public class MemChild  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private String name;
     private Date dob;
     private String sex;
     private boolean hoi;
     private boolean aci;
     private boolean status;

    public MemChild() {
    }

	
    public MemChild(Member member, String sex, boolean hoi, boolean aci, boolean status) {
        this.member = member;
        this.sex = sex;
        this.hoi = hoi;
        this.aci = aci;
        this.status = status;
    }
    public MemChild(Member member, String name, Date dob, String sex, boolean hoi, boolean aci, boolean status) {
       this.member = member;
       this.name = name;
       this.dob = dob;
       this.sex = sex;
       this.hoi = hoi;
       this.aci = aci;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public boolean isHoi() {
        return this.hoi;
    }
    
    public void setHoi(boolean hoi) {
        this.hoi = hoi;
    }
    public boolean isAci() {
        return this.aci;
    }
    
    public void setAci(boolean aci) {
        this.aci = aci;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


