package com.court.model;
// Generated Apr 23, 2017 7:05:18 PM by Hibernate Tools 4.3.1

/**
 * PrivCat generated by hbm2java
 */
public class PrivCat implements java.io.Serializable {

    private Integer id;
    private UserRole userRole;
    private UsrRolePrivilage usrRolePrivilage;
    private String actionName;
    private boolean actionStatus;

    public PrivCat() {
    }

    public PrivCat(UserRole userRole, UsrRolePrivilage usrRolePrivilage, boolean actionStatus) {
        this.userRole = userRole;
        this.usrRolePrivilage = usrRolePrivilage;
        this.actionStatus = actionStatus;
    }

    public PrivCat(UserRole userRole, UsrRolePrivilage usrRolePrivilage, String actionName, boolean actionStatus) {
        this.userRole = userRole;
        this.usrRolePrivilage = usrRolePrivilage;
        this.actionName = actionName;
        this.actionStatus = actionStatus;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public UserRole getUserRole() {
        return this.userRole;
    }

    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }

    public UsrRolePrivilage getUsrRolePrivilage() {
        return this.usrRolePrivilage;
    }

    public void setUsrRolePrivilage(UsrRolePrivilage usrRolePrivilage) {
        this.usrRolePrivilage = usrRolePrivilage;
    }

    public String getActionName() {
        return this.actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    public boolean isActionStatus() {
        return this.actionStatus;
    }

    public void setActionStatus(boolean actionStatus) {
        this.actionStatus = actionStatus;
    }

}
