package com.court.model;
// Generated Apr 18, 2017 4:12:00 PM by Hibernate Tools 4.3.1



/**
 * UserHasUserRole generated by hbm2java
 */
public class UserHasUserRole  implements java.io.Serializable {


     private Integer id;
     private User user;
     private UserRole userRole;

    public UserHasUserRole() {
    }

    public UserHasUserRole(User user, UserRole userRole) {
       this.user = user;
       this.userRole = userRole;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public UserRole getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(UserRole userRole) {
        this.userRole = userRole;
    }




}


