package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;
     private String fullName;
     private String email;
     private String address;
     private String tel;
     private String imgPath;
     private boolean status;
     private Set<UserHasUserRole> userHasUserRoles = new HashSet<>();

    public User() {
    }

	
    public User(String userName, boolean status) {
        this.userName = userName;
        this.status = status;
    }
    public User(String userName, String password, String fullName, String email, String address, String tel, String imgPath, boolean status, Set<UserHasUserRole> userHasUserRoles) {
       this.userName = userName;
       this.password = password;
       this.fullName = fullName;
       this.email = email;
       this.address = address;
       this.tel = tel;
       this.imgPath = imgPath;
       this.status = status;
       this.userHasUserRoles = userHasUserRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getImgPath() {
        return this.imgPath;
    }
    
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set<UserHasUserRole> getUserHasUserRoles() {
        return this.userHasUserRoles;
    }
    
    public void setUserHasUserRoles(Set<UserHasUserRole> userHasUserRoles) {
        this.userHasUserRoles = userHasUserRoles;
    }




}


