package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private Integer id;
     private String roleName;
     private boolean status;
     private Set<PrivCat> privCats = new HashSet<PrivCat>(0);
     private Set<UserHasUserRole> userHasUserRoles = new HashSet<>();

    public UserRole() {
    }

	
    public UserRole(boolean status) {
        this.status = status;
    }
    public UserRole(String roleName, boolean status, Set<PrivCat> privCats, Set<UserHasUserRole> userHasUserRoles) {
       this.roleName = roleName;
       this.status = status;
       this.privCats = privCats;
       this.userHasUserRoles = userHasUserRoles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set<PrivCat> getPrivCats() {
        return this.privCats;
    }
    
    public void setPrivCats(Set<PrivCat> privCats) {
        this.privCats = privCats;
    }
    public Set<UserHasUserRole> getUserHasUserRoles() {
        return this.userHasUserRoles;
    }
    
    public void setUserHasUserRoles(Set<UserHasUserRole> userHasUserRoles) {
        this.userHasUserRoles = userHasUserRoles;
    }




}


