package com.court.model;
// Generated Oct 9, 2017 7:04:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsrRolePrivilage generated by hbm2java
 */
public class UsrRolePrivilage  implements java.io.Serializable {


     private Integer id;
     private int privId;
     private String privName;
     private boolean status;
     private Set<PrivCat> privCats = new HashSet<>();

    public UsrRolePrivilage() {
    }

	
    public UsrRolePrivilage(int privId, boolean status) {
        this.privId = privId;
        this.status = status;
    }
    public UsrRolePrivilage(int privId, String privName, boolean status, Set<PrivCat> privCats) {
       this.privId = privId;
       this.privName = privName;
       this.status = status;
       this.privCats = privCats;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPrivId() {
        return this.privId;
    }
    
    public void setPrivId(int privId) {
        this.privId = privId;
    }
    public String getPrivName() {
        return this.privName;
    }
    
    public void setPrivName(String privName) {
        this.privName = privName;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set<PrivCat> getPrivCats() {
        return this.privCats;
    }
    
    public void setPrivCats(Set<PrivCat> privCats) {
        this.privCats = privCats;
    }




}


